# SPDX-License-Identifier: GPL-2.0-only

MODULE_NAME_GPIO_KEY = amlogic-input-gpiokey
obj-$(CONFIG_AMLOGIC_GPIO_KEY)  = $(MODULE_NAME_GPIO_KEY).o
$(MODULE_NAME_GPIO_KEY)-y = gpio_keypad.o

MODULE_NAME_ADC_KEY = amlogic-input-adckey
obj-$(CONFIG_AMLOGIC_ADC_KEYPADS)  += $(MODULE_NAME_ADC_KEY).o
$(MODULE_NAME_ADC_KEY)-y = adc_keypad.o
