# SPDX-License-Identifier: GPL-2.0-only

MODULE_NAME = amlogic-input-gpiokey
obj-$(CONFIG_AMLOGIC_GPIO_KEY)  = $(MODULE_NAME).o
$(MODULE_NAME)-y += gpio_keypad.o

MODULE_NAME = amlogic-input-adckey
obj-$(CONFIG_AMLOGIC_ADC_KEYPADS)  = $(MODULE_NAME).o
$(MODULE_NAME)-y += adc_keypad.o
