# SPDX-License-Identifier: GPL-2.0-or-later
#
#Makefile for the amlogic DVB aucpu driver
#

MODULE_NAME = amlogic-aucpu
obj-$(CONFIG_AMLOGIC_AUCPU) = $(MODULE_NAME).o

$(MODULE_NAME)-y += aml_aucpu.o
