# SPDX-License-Identifier: GPL-2.0
load("//common:common_drivers/project/project.bzl", "UPGRADE_PROJECT", "GKI_MODULES_OUT_REMOVE")

AMLOGIC_MODULES = [
]

GKI_MODULES_OUT_REMOVE_R = [
    "kernel/kheaders.ko",
]

GKI_MODULES_OUT_REMOVE_S = [
]

GKI_MODULES_OUT_REMOVE_P = [
    "drivers/net/mii.ko",
    "kernel/kheaders.ko",
]

GKI_MODULES_OUT_REMOVE_U = [
]

ALL_MODULES_REMOVE = \
	GKI_MODULES_OUT_REMOVE + GKI_MODULES_OUT_REMOVE_R if UPGRADE_PROJECT == "r" or UPGRADE_PROJECT == "R" else \
	GKI_MODULES_OUT_REMOVE + GKI_MODULES_OUT_REMOVE_S if UPGRADE_PROJECT == "s" or UPGRADE_PROJECT == "S" else \
	GKI_MODULES_OUT_REMOVE + GKI_MODULES_OUT_REMOVE_P if UPGRADE_PROJECT == "p" or UPGRADE_PROJECT == "P" else \
	GKI_MODULES_OUT_REMOVE + GKI_MODULES_OUT_REMOVE_U if UPGRADE_PROJECT == "u" or UPGRADE_PROJECT == "U" else \
	GKI_MODULES_OUT_REMOVE
