# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
MEDIA_MODULE_NAME = amlogic-media
obj-$(CONFIG_AMLOGIC_MEDIA_MODULE) = $(MEDIA_MODULE_NAME).o
$(MEDIA_MODULE_NAME)-y = media_main.o

include $(COMMON_DRIVERS_DIR)/drivers/media/common/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/gdc/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/osd/Makefile

