# SPDX-License-Identifier: GPL-2.0
dtb-y += s4d_s905y4_ap222_drm.dtb
dtb-y += c2_c305x_af400.dtb
dtb-y += a1-a113l-ad401.dtb
dtb-y += a1-a113l-ad409.dtb
dtbo-y += android_overlay_dt.dtbo
dtb-y += a1-a113l-ad403.dtb
dtb-y += sc2_s905x4_ah212_drm.dtb
