# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

MODULE_NAME = amlogic-power-common
obj-$(CONFIG_AMLOGIC_COMMON_POWER)		+= $(MODULE_NAME).o
$(MODULE_NAME)-y += sec_pwr_ctrl.o sec_power_domain.o power_domain_sysfs.o