# SPDX-License-Identifier: GPL-2.0

# obj-$(CONFIG_AMLOGIC_CRG)             += crgdrdphy/
# obj-$(CONFIG_AMLOGIC_CRG)             += crgm31phy/
obj-$(CONFIG_AMLOGIC_USB2PHY) 		+= usb2phy/
obj-$(CONFIG_AMLOGIC_USBPHY) 		+= usb3v2phy/
obj-$(CONFIG_AMLOGIC_USBPHYC2)		+= usbc2phy/
# obj-$(CONFIG_AMLOGIC_USB3PHY) 	+= usb3v3phy/
obj-$(CONFIG_AMLOGIC_USB3PHY) 		+= usbotg/
obj-$(CONFIG_AMLOGIC_CC)                += cc/
obj-$(CONFIG_AMLOGIC_BC)                += bc/
obj-$(CONFIG_AMLOGIC_CRG)               += crg/
obj-$(CONFIG_AMLOGIC_USB_DWC_OTG_HCD)	+= dwc_otg/310/