# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX_COMMON) += vout/hdmitx_common/hdmitx_boot_parameters.o \
							vout/hdmitx_common/hdmitx_common.o \
							vout/hdmitx_common/hdmitx_drm_hook.o
