# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX_COMMON) += \
							vout/hdmitx_common/hdmitx_boot_parameters.o \
							vout/hdmitx_common/hdmitx_common.o \
							vout/hdmitx_common/hdmitx_drm_hook.o \
							vout/hdmitx_common/hdmitx_sysfs_common.o \
							vout/hdmitx_common/hdmitx_edid.o \
							vout/hdmitx_common/hdmitx_hw_common.o \
							vout/hdmitx_common/hdmitx_packet.o \
							vout/hdmitx_common/hdmitx_mode.o \
							vout/hdmitx_common/hdmitx_format_para.o \
							vout/hdmitx_common/hdmitx_mode_set.o \
							vout/hdmitx_common/hdmitx_audio.o \
							vout/hdmitx_common/hdmitx_tracer_linux.o \
							vout/hdmitx_common/hdmitx_event_mgr_linux.o \
							vout/hdmitx_common/hdmitx_log.o \
							vout/hdmitx_common/hdmitx_compliance.o
