# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

MODULE_NAME = amlogic-watchdog
obj-$(CONFIG_AMLOGIC_MESON_GXBB_WATCHDOG) = $(MODULE_NAME).o
$(MODULE_NAME)-y += meson_gxbb_wdt.o

MODULE_NAME = amlogic-smc-watchdog
obj-$(CONFIG_AMLOGIC_ARM_SMC_WATCHDOG) = $(MODULE_NAME).o
$(MODULE_NAME)-y += arm_smc_wdt.o
