# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#Ascending by module name's ASCII
include $(COMMON_DRIVERS_DIR)/drivers/media/common/arch/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/canvas/Makefile

