# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#Ascending by module name's ASCII
include $(COMMON_DRIVERS_DIR)/drivers/media/common/arch/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/canvas/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/ge2d/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/ion_dev/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/codec_mm/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/vfm/Makefile

