# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
#Makefile for the Smart card driver.
#
MODULE_NAME = amlogic-smartcard-sc2
obj-$(CONFIG_AMLOGIC_SMARTCARD) = $(MODULE_NAME).o

#ccflags-y += -I$(srctree)/$(COMMON_DRIVERS_DIR)/include

$(MODULE_NAME)-y += smartcard.o
