# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_AMLOGIC_AMLTEE) += tee.o
tee-objs += tee_core.o
tee-objs += tee_shm.o
tee-objs += tee_shm_pool.o
tee-objs += tee_data_pipe.o
obj-$(CONFIG_AMLOGIC_OPTEE) += optee/
