# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_AMBILIGHT) += vout/lcd/ambilight/ambilight_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_AMBILIGHT) += vout/lcd/ambilight/ambilight_debug.o
