# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += cabc/
# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += aad/
# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += pregm/
# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += hdr10_tmo/
# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += blue_stretch/
# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += cuva/
# obj-$(CONFIG_AMLOGIC_MEDIA_COMMON_ALGORITHM) += color_tune/

include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/cabc/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/aad/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/pregm/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/hdr10_tmo/Makefile
#include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/blue_stretch/Makefile
#include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/cuva/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/algorithm/common/color_tune/Makefile

