# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

MODULE_NAME = amlogic-irblaster
obj-$(CONFIG_AMLOGIC_IRBLASTER) = $(MODULE_NAME).o
$(MODULE_NAME)-y += core.o
$(MODULE_NAME)-y += sysfs.o
$(MODULE_NAME)-y += irblaster-meson.o
