#
# AMLOGIC DSC DECODER
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_DSC_DEC) += vin/tvin/dsc_dec/dsc_dec_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_DSC_DEC) += vin/tvin/dsc_dec/dsc_dec_config.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_DSC_DEC) += vin/tvin/dsc_dec/dsc_dec_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_DSC_DEC) += vin/tvin/dsc_dec/dsc_dec_debug.o

